Repository Poeschl-HomeAssistant-Addons/syncthing, pull requests merged in 2025-09, with the labels that each got.

#18 docs: tweaks
  syncthing/DOCS.md
Labels: documentation

#19 ⬆️ Update syncthing to 2.0.6
  syncthing/Dockerfile
Labels: dependencies

#22 🐛 Fix restart loops by waiting for healthy Syncthing
  syncthing/root/etc/s6-overlay/s6-rc.d/syncthing-setup/run
  syncthing/root/etc/s6-overlay/s6-rc.d/syncthing-setup/up
Labels: bugfix
